[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
[functions."api"]
  external_node_modules = ["@libsql/client", "@libsql/client/web"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
